### ISSUE TITLE
punycode DeprecationWarning

### ISSUE THREAD

**Issue by JakeHedman** [libsql/isomorphic-ts#4]
node-fetch is causing deprecation warnings in node 21

```(node:1249861) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.```

**Comment by matthewp** [comment]
I ran into this as well, upgrading to `node-fetch` 3 should fix it. The upgrade guide makes it seem pretty simple to me: https://github.com/node-fetch/node-fetch/blob/HEAD/docs/v3-UPGRADE-GUIDE.md
